spring.application.name=MilkyWay

instagram.session-id=
instagram.csrf-token=
instagram.user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram/303.0.0.11.109
